sudo: required
dist: trusty

language: python
python:
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install postgis
  - sudo apt-get install graphicsmagick-imagemagick-compat
  - sudo apt-get install libimage-exiftool-perl

install:
  - pip install -e .

script:
  - ./tests/tools/test_all.sh
