#! /usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import yaml
import argparse
from flask import Flask

from pxserver.utils import draw_map
from pxserver.database import Database


if __name__ == '__main__':
    # arg parse
    descr = 'Draw a map with all images available in the database'
    parser = argparse.ArgumentParser(description=descr)

    cfg_help = 'configuration file'
    parser.add_argument('cfg', metavar='cfg', type=str, help=cfg_help)

    map_help = 'output file'
    parser.add_argument('map', metavar='map', type=str, help=map_help)

    args = parser.parse_args()

    # open config file
    ymlconf_db = None
    with open(args.cfg, 'r') as f:
        try:
            ymlconf_db = yaml.load(f)['flask']
        except:
            print("ERROR: ", sys.exc_info()[0])
            f.close()
            sys.exit()

    # database connection
    app = Flask(__name__)
    with app.app_context():
        app.config = ymlconf_db
        app.config['LOGGER_NAME'] = 'scan'
        Database.init_app(app)

        # draw map
        draw_map(args.map)
