#! /bin/bash

# -----------------------------------------------------------------------------
# read cli
# -----------------------------------------------------------------------------
while [ $# -gt 1 ]
do
  key="$1"

  case $key in
    --input)
      INPUT_DIR="$2"
      shift
     ;;

    --output)
      OUTPUT_DIR="$2"
      shift
    ;;
  esac

  shift
done

if [ -z "$INPUT_DIR" ] || [ -z "$OUTPUT_DIR" ]
then
    echo "Invalid usage: "
    echo "  pxvips.sh --input <input_dir> --output <output_dir>"
    exit
fi

# -----------------------------------------------------------------------------
# vips
# -----------------------------------------------------------------------------
FILES=$(find $INPUT_DIR -regex ".*\.\(jpg\|gif\|png\|jpeg\)")

for f in $FILES
do
  echo "Converting $f..."
  FILENAME=$(basename $f)
  FILENAME_BASE=$(echo $FILENAME | cut -f 1 -d '.')
  FILENAME_DIR=$(dirname $f)
  OUTPUT_SUBDIR=${FILENAME_DIR#$INPUT_DIR}
  TIFF=$OUTPUT_DIR/$OUTPUT_SUBDIR/$FILENAME_BASE.tif

  # create output subdirectory
  mkdir -p $OUTPUT_DIR/$OUTPUT_SUBDIR

  # convert images in tiled mutli-resolution tiff images
  eval "convert $f -define tiff:tile-geometry=256x256 -compress jpeg 'ptif:$TIFF'"
  # vips im_vips2tiff $f $TIFF:deflate,tile:256x256,pyramid

  # convert/vips doesn't keep GPSInfo metadata. So we keep it manually
  exiftool -TagsFromFile $f "-all:all>all:all" $TIFF

  # remove exiftool copy
  rm -f $TIFF_original
done
